### ISSUE TITLE
checksums for binaries

### ISSUE THREAD

**Issue by f5-rahm** [innov8rz-ftc-team-11039/TeleDrive#4]
Can you make checksums for the binaries available?

**Comment by f5-rahm** [comment]
It would also be good to get a team coach/mentor to sign off in the readme that this software does only what it says it does since the source is not available to review publicly and cameras are involved.

**Comment by mihir-chauhan** [comment]
The camera feed is handled through Parsec or Zoom or whichever service you choose to use. Our software does not connect to the camera, it only sends the gamepad control commands over the Internet.

**Comment by f5-rahm** [comment]
thanks for the info. Would still like to see checksums made available for the binaries though.
