### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by aleksrutins** [innov8rz-ftc-team-11039/TeleDrive#5]
Hello,

Is there a possibility that you could build this for Linux systems? (or opensource the macOS version so that us Linux users can can do the porting ourselves?)

I use Linux, so I would like to be able to remotely drive our team's robot _without_ booting into Windows.

Thanks!

**Comment by mihir-chauhan** [comment]
Hi @aleksrutins ,

There is a new version of TeleDrive that will be released very soon which will be open-source. Hope it helps!

**Comment by mihir-chauhan** [comment]
Hi @aleksrutins, I have just released TeleDrive 2.0 which is an open-source project so you can easily run it on Linux as well. Please find the repository here: https://github.com/innov8rz-ftc-team-11039/TeleDrive-2.0. Hope this helps!
