### ISSUE TITLE
Reqesting source code

### ISSUE THREAD

**Issue by ninjabelt52** [innov8rz-ftc-team-11039/TeleDrive#6]
Could I get the source code for this, or even maybe for teledrive 2.0? I'm trying to set this up more like to the 2.0 version, but since the servers are down, I would like to know how to set this up on my own server. Could someone maybe walk me through the process?

**Comment by mihir-chauhan** [comment]
Hi Boen, Thanks for reaching out about TeleDrive. We plan to post the source code for this repository soon. TeleDrive 2.0 source code is completely open to the public (both server and the main app). We will chat more through email. Thanks again!
